### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by mikeekim97271** [jkctech/WiiHero#3]
the program does not want to start, nothing happens. Tried all compatibility settings, administrator mode. no matter which exe. file, whether in the "release" or "debug" folder. there is no exe in the main folder. file.
Please help

**Comment by jkctech** [comment]
Judging on your message (which is hard, please learn how to ask questions properly) you cloned the repo and looking for an exe?

Have you tried using **actual** the release?
https://github.com/jkctech/WiiHero/releases

What operating system are you using? If you HAVE been using the release, did you forget to keep the library files together with the executable by chance?

Troubleshooting your problem is literally impossible without proper information about what you are doing EXACTLY and your EXACT setup and process.

Can't fix what I don't understand
